#1.prepare 

- name: Import repository gpg key
  shell: 
    wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -

#2. install InfluxDB     

- block:
  - name: Configure InfluxDB repo
    shell:
      echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} \
      stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

  - name: Install InfluxDB
    apt:
      name: influxdb
      update_cache: yes


#  InfluxDB web GUI : chronograf
  - name: Install chronograf
    shell: |
      wget  https://dl.influxdata.com/chronograf/releases/chronograf_{{influxdb_version}}_amd64.deb
      dpkg -i chronograf_{{influxdb_version}}_amd64.deb
     