#1.prepare 

- name: Import repository gpg key
  shell: 
    wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -

#2. install InfluxDB     

- block:
  - name: Configure InfluxDB repo
    shell:
      echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} \
      stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

  - name: Install InfluxDB
    apt:
      name: influxdb
      update_cache: yes


#  InfluxDB web GUI : chronograf
  - name: Install chronograf
    unarchive:
      src: "https://dl.influxdata.com/influxdb/releases/influxdb_{{influxdb_download_version}}_amd64.deb"
      dest: /usr/lib/
      remote_src: yes
      owner: influxdb
      group: influxdb
     