# install InfluxDB by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure InfluxDB


- name: Restart influxdb,Chronograf
  service:
    name: influxdb chronograf
    state: restarted
    enabled: yes

      
# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /usr/lib/influxdb   /data/wwwroot/influxdb
    ln -sb /etc/influxdb/influxdb.conf   /data/config/influxdb
    ln -sb /var/log/influxdb/influxd.log   /data/logs/influxdb
# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check InfluxDB Version
    shell: echo `influx -version` >> /data/logs/install_version.txt


# check service state
- name: Check chronograf Service
  shell: systemctl status chronograf | grep Active*
  register: check_chronograf_service
  notify: check_chronograf_service

- name: Check InfluxDB Service
  shell: systemctl status influxdb | grep Active*
  register: check_influxdb_service
  notify: check_influxdb_service

