#1.install InfluxDB

- name: Configure influxdb repo
  yum_repository: 
    name: InfluxDB Repository - RHEL \$releasever
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgcheck: https://repos.influxdata.com/influxdb.key
    enabled:  yes

- block:
  - name: Install InfluxDB
    yum:
      name: influxdb
      update_cache: yes
  
  - name: Install InfluxDB web GUI
    yum:
      name: chronograf
      