#1.prepare

- name: Import key
  shell: rpm --import https://repos.influxdata.com/influxdb.key

- name: Configure influxdb repo
  yum_repository: 
    name: influxdb
    description: InfluxDB Repository - RHEL \$releasever
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgcheck: yes
    enabled:  yes

# install InfluxDB

- block:
  - name: Install InfluxDB
    yum:
      name: influxdb
      update_cache: yes
      state: latest

# InfluxDB web GUI: chronograf
  - name: Install InfluxDB web GUI
    shell: |
      wget https://dl.influxdata.com/chronograf/releases/chronograf-{{chronograf_version}}.x86_64.rpm
      rpm -ivh chronograf-{{chronograf_version}}.x86_64.rpm
      