#1.install InfluxDB

- name: Configure influxdb repo
  yum_repository: 
    name: influxdb
    description: InfluxDB Repository - RHEL \$releasever
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgcakey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes
    enabled:  yes


- block:
  - name: Install InfluxDB
    yum:
      name: influxdb
      update_cache: yes
      state: latest
  
  - name: Install InfluxDB web GUI
    yum:
      name: chronograf
      