# install InfluxDB by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure InfluxDB

- name: Create Influxdb User
  user:
    name: Influxdb
    shell: /usr/sbin/nologin
    home: /data/wwwroot/Influxdb
    create_home: no

- name: Create Influxdb directory
  file:
    path: /data/wwwroot/Influxdb
    state: directory
    owner: Influxdb
    group: Influxdb
    
- name: Download Influxdb
  get_url:
    dest: /data/wwwroot/Influxdb
    url: "{{Influxdb_download_url}}"
    owner: Influxdb
    group: Influxdb

- name: Set Influxdb config
  template:
    src: Influxdb.conf.jinja2
    dest: /data/wwwroot/Influxdb/Influxdb.conf
    owner: Influxdb
    group: Influxdb

- name: Setting Influxdb service
  copy:
    src: Influxdb.service
    dest: /lib/systemd/system/Influxdb.service

- name: Restart Influxdb
  service:
    name: Influxdb.service
    state: restarted
    enabled: yes

- name: Create Influxdb System User
  user:
      name: Influxdb 
      create_home: no 
      home: /opt/Influxdb
      shell: /usr/sbin/nologin

- name: Download Influxdb
  unarchive:
      src: "{{Influxdb_download_url}}"
      dest: /opt/ 
      group: Influxdb 
      remote_src: yes
      owner: Influxdb
      mode: g+w

- name: Create the storage directory for files.
  file:
      path: /opt/Influxdb/data
      state: directory 
      owner: Influxdb 
      group: Influxdb
      mode: g+w
      
- name: Set database connection /opt/Influxdb/config/config.json
  lineinfile:
    dest: /opt/Influxdb/config/config.json
    regexp: '"DataSource":'
    line: '    "DataSource": "{{Influxdb_db_user}}:{{Influxdb_db_password}}@tcp(localhost:3306)/{{Influxdb_db_name}}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",'
    backrefs: yes 

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /opt/Influxdb  /data/wwwroot/Influxdb
    ln -sb /opt/Influxdb/config /data/config/Influxdb

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check InfluxDB Version
    shell: sudo sh -c "Influxdbctl status | grep 'InfluxDB version' 1>> /data/logs/install_version.txt"

  - name: Check Erlang Version
    shell: sudo sh -c 'echo "Erlang $(yum info erlang | grep Version | sed -n 1p)" 1>> /data/logs/install_version.txt'
    when: ansible_os_family=="RedHat"

# check service state
- name: Check InfluxDB Service
  shell: systemctl status Influxdb | grep Active*
  register: check_Influxdb_service
  notify: check_Influxdb_service
